### ISSUE TITLE
Unprocessable Entity is not a helpful error message

### ISSUE THREAD

**Issue by johnjeffers** [jenkinsci/kubernetes-cd-plugin#102]
Getting this error when trying to deploy.

```
Starting Kubernetes deployment
ERROR: ERROR: java.lang.RuntimeException: io.kubernetes.client.ApiException: Unprocessable Entity
```

We don't see what's wrong with our deployment. Is there any way to have the error message include the line(s) that caused the error?

**Comment by gavinfish** [comment]
@johnjeffers Could you please provide the sample to reproduce this issue?

**Comment by johnjeffers** [comment]
We suspect it was malformed YAML. Here's a sample:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
  labels:
    app: my-app
    team: ops
    environment: stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
       app: my-app
       team: ops
       environment: stg
    spec:
      containers:
      - name: my-app
      ...
```

Items under `spec.template.metadata.labels` had the wrong indent. Obviously this is our fault, and the person responsible could have caught this with a YAML linter.

It would be very helpful if the error message indicated the line number at which it encountered the problem, or even something indicating it was malformed YAML. "Unprocessable Entity" is too vague.

Thank you!
