### ISSUE TITLE
Second deploy isn't working

### ISSUE THREAD

**Issue by papezt** [jenkinsci/kubernetes-cd-plugin#13]
Hi,
we are using this plugin in pipeline and it's pretty simple but we have issue in our flow: 
- build new image with tag :latest
- upload to registry
- run deploy to k8s

First deploy is fine app is running... But on second try Jenkins is green, everything looks fine but our pods are not on latest code and I don't know how to debug this because in Jenkins build log is just: _Finished Kubernetes deployment_. 

Our Deployment.yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: stage-api-deployment
    labels:
        app: stage-api
        tier: backend
        maintainer: team1
spec:
    replicas: 2
    selector:
        matchLabels:
            app: stage-api
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: stage-api
        spec:
            containers:
                - name: stage-api
                  image: ****.azurecr.io/api:staging
                  imagePullPolicy: Always
                  readinessProbe:
                    httpGet:
                      path: /health
                      port: 8080
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  env:
                      - name: profile
                        value: 'staging'
                      - name: logname
                        value: 'gce'
                  ports:
                    - containerPort: 8080
            imagePullSecrets:
                - name: regsecret
```
Thanks for help.
