### ISSUE TITLE
topologyKeys not supported

### ISSUE THREAD

**Issue by Trojaner** [jenkinsci/kubernetes-cd-plugin#131]
Kubernetes v1.17 has added "topologyKeys" to services
(e.g.:

```yml
apiVersion: v1
kind: Service
...
spec:
  ...
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"
```

However, using this results in the following error:
`Unable to find property 'topologyKeys' on class: io.kubernetes.client.openapi.models.V1ServiceSpec`

More information:
https://imroc.io/posts/kubernetes/service-topology-en/
