### ISSUE TITLE
Plugin drops environment variables!

### ISSUE THREAD

**Issue by dabeck** [jenkinsci/kubernetes-cd-plugin#47]
I just recognized that the plugin drops environment variables defined in the deployment.yml:

My deployment.yml looks like this: 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name service
spec:
  replicas: 1
    spec:
      containers:
      - name: service
        env:
          - name: MONGODB_SERVER
            value: mongodb
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: user
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: password
```

Jenkins logs states the envVars are actually there:
```
Applied Deployment: Deployment(apiVersion=extensions/v1beta1, kind=Deployment, [...], spec=DeploymentSpec(..), ...,
containers=[Container(args=[], command=[], env=[EnvVar(name=MONGODB_SERVER, value=mongodb, valueFrom=null, additionalProperties={}), EnvVar(name=MONGODB_USERNAME, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=null, resourceFieldRef=null, secretKeyRef=SecretKeySelector(key=user, name=mongodb, optional=null, additionalProperties={}), additionalProperties={}), additionalProperties={}), EnvVar(name=MONGODB_PASSWORD, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=null, resourceFieldRef=null, secretKeyRef=SecretKeySelector(key=password, name=mongodb, optional=null, additionalProperties={}), additionalProperties={}), additionalProperties={})], envFrom=[],
[...]
```

but when I do a `kubectl get deployment ... -o yaml` it does NOT contain the env vars anymore...
