### ISSUE TITLE
Expecting to have "Kubernetes Namespace for Secret" support system variable

### ISSUE THREAD

**Issue by grantsunny** [jenkinsci/kubernetes-cd-plugin#83]
We currently have pipeline create and deploy services in namespaces according the branch-name and we found there is a small gap prevent us to make things perfect. 

That is, when I run the whole stuff in default namespace I am able to leverage $KUBERNETES_SECRET_NAME but when I am using system variable as the name of namespaces dynamically and deploy things inside the namespace, I found I just cannot use system variable in the field "Kubernetes Namespace for Secret" field. 

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ${KUBERNETES_NS}
  labels:
    name: ${KUBERNETES_NS}
```
And I put ${KUBERNETES_NS} in the configuration field "Kubernetes Namespace for Secret" but it seems this configuration does not honor the system parameters configuration. 

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-k8s-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-k8s-app
    spec:
      containers:
      - name: sample-k8s-app-container
        image: <username or registry URL>/<image_name>:<tag(maybe $BUILD_NUMBER)>
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
```
Will appreciate if anyone could have a look and provide a suggestion on this. Thank you!
